#!/bin/bash
INBOX=``/inbox/``
OUTBOX=``/outbox/``

CHNGEDATE=$(stat --format '%y' $INBOX |grep -Eo '[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}')
CHNGETIME=$(stat --format '%y' $INBOX |grep -Eo '[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}')

mkdir -p $OUTBOX$CHNGEDATE/
if [ $? -eq 0 ]
  then  
    echo Directory creation success!
  else
    echo Directory creation failed! Code=$?.
    exit
fi
cd $OUTBOX$CHNGEDATE/

#touch $CHNGETIME-errors.txt
echo $(grep  'error' $INBOX/*.log) >> $CHNGETIME-errors.txt
if [ $? -eq 0 ]
  then  
    echo Errors adding success!
  else
    echo Errors adding failed! Code=$?.
    exit
fi

if [ -e $CHNGETIME.files.tar.gz]
  then
    echo Archive already exists!
    exit
  else
    tar cvzf $CHNGETIME.files.tar.gz $INBOX
if [ $? -eq 0 ]
  then
    rm $INBOX/*
  else 
    echo Archive creation failed! Code=$?.
    exit
fi
if [ $? -eq 0 ]
  then
    echo Backup execution success! Code=$?.
  else 
    echo Backup execution failed! Code=$?.
    exit
fi
